// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf.proto

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	protobuf.proto

It has these top-level messages:
	Request
	Response
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Type             []byte   `protobuf:"bytes,1,req,name=type" json:"type,omitempty"`
	Norf             []byte   `protobuf:"bytes,2,req,name=norf" json:"norf,omitempty"`
	Snon             []byte   `protobuf:"bytes,3,opt,name=snon" json:"snon,omitempty"`
	Enpk             []byte   `protobuf:"bytes,4,opt,name=enpk" json:"enpk,omitempty"`
	List             [][]byte `protobuf:"bytes,5,rep,name=list" json:"list,omitempty"`
	Smsg             []byte   `protobuf:"bytes,6,req,name=smsg" json:"smsg,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetType() []byte {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Request) GetNorf() []byte {
	if m != nil {
		return m.Norf
	}
	return nil
}

func (m *Request) GetSnon() []byte {
	if m != nil {
		return m.Snon
	}
	return nil
}

func (m *Request) GetEnpk() []byte {
	if m != nil {
		return m.Enpk
	}
	return nil
}

func (m *Request) GetList() [][]byte {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *Request) GetSmsg() []byte {
	if m != nil {
		return m.Smsg
	}
	return nil
}

type Response struct {
	Type             []byte             `protobuf:"bytes,1,req,name=type" json:"type,omitempty"`
	Cora             []byte             `protobuf:"bytes,2,req,name=cora" json:"cora,omitempty"`
	Keys             []*ResponseAllkeys `protobuf:"bytes,3,rep,name=keys" json:"keys,omitempty"`
	Smsg             []byte             `protobuf:"bytes,4,req,name=smsg" json:"smsg,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetType() []byte {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Response) GetCora() []byte {
	if m != nil {
		return m.Cora
	}
	return nil
}

func (m *Response) GetKeys() []*ResponseAllkeys {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *Response) GetSmsg() []byte {
	if m != nil {
		return m.Smsg
	}
	return nil
}

type ResponseAllkeys struct {
	Pub              []byte `protobuf:"bytes,1,req,name=pub" json:"pub,omitempty"`
	Enk              []byte `protobuf:"bytes,2,req,name=enk" json:"enk,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ResponseAllkeys) Reset()                    { *m = ResponseAllkeys{} }
func (m *ResponseAllkeys) String() string            { return proto.CompactTextString(m) }
func (*ResponseAllkeys) ProtoMessage()               {}
func (*ResponseAllkeys) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *ResponseAllkeys) GetPub() []byte {
	if m != nil {
		return m.Pub
	}
	return nil
}

func (m *ResponseAllkeys) GetEnk() []byte {
	if m != nil {
		return m.Enk
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "protobuf.request")
	proto.RegisterType((*Response)(nil), "protobuf.response")
	proto.RegisterType((*ResponseAllkeys)(nil), "protobuf.response.allkeys")
}

func init() { proto.RegisterFile("protobuf.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0xbf, 0x4e, 0xc7, 0x20,
	0x14, 0x85, 0xc3, 0x0f, 0xb4, 0x0d, 0x1a, 0x63, 0x98, 0x48, 0x27, 0xd2, 0xa9, 0x8b, 0x0c, 0x3e,
	0x4a, 0xdf, 0xa0, 0x35, 0xb7, 0xc6, 0xb4, 0x02, 0x02, 0x1d, 0x3a, 0xfa, 0x30, 0xbe, 0xa7, 0x39,
	0xf4, 0x8f, 0x93, 0xdb, 0xc7, 0x97, 0xc3, 0x3d, 0xf7, 0xca, 0xa7, 0x10, 0x7d, 0xf6, 0xe3, 0x3a,
	0xd9, 0x02, 0xaa, 0x3e, 0xdf, 0xed, 0x37, 0x93, 0x55, 0xa4, 0xaf, 0x95, 0x52, 0x56, 0x4a, 0x8a,
	0xbc, 0x05, 0xd2, 0xcc, 0xdc, 0xba, 0xc7, 0xbe, 0x30, 0x9c, 0xf3, 0x71, 0xd2, 0xb7, 0xdd, 0x81,
	0xe1, 0x92, 0xf3, 0x4e, 0x73, 0xc3, 0xe0, 0xc0, 0x70, 0xe4, 0xc2, 0xac, 0xc5, 0xee, 0xc0, 0x70,
	0xcb, 0x47, 0xca, 0xfa, 0xce, 0x70, 0x38, 0x70, 0xf9, 0xfb, 0x99, 0xde, 0xf5, 0xfd, 0x3e, 0x0f,
	0xdc, 0xfe, 0x30, 0x59, 0x47, 0x4a, 0xc1, 0xbb, 0x44, 0xff, 0x2d, 0xf1, 0xe6, 0xe3, 0x70, 0x2e,
	0x01, 0x56, 0x56, 0x8a, 0x99, 0xb6, 0xa4, 0xb9, 0xe1, 0xdd, 0xc3, 0x6b, 0x63, 0xaf, 0x0b, 0xcf,
	0x49, 0x76, 0x58, 0x16, 0x24, 0xfa, 0x92, 0xbb, 0x8a, 0xc5, 0x5f, 0x71, 0xf3, 0x22, 0xab, 0x23,
	0xa4, 0x9e, 0x25, 0x0f, 0xeb, 0x78, 0xb4, 0x02, 0x61, 0xc8, 0xcd, 0x47, 0x27, 0xf0, 0x37, 0x00,
	0x00, 0xff, 0xff, 0xb9, 0x90, 0xab, 0x34, 0x46, 0x01, 0x00, 0x00,
}
